os: linux
language: elixir
elixir: 1.12.1
otp_release: 24.0.1
cache:
  directories:
    - _build
    - deps
script:
  - mix format --check-formatted || travis_terminate 1
  - mix test --trace || travis_terminate 1
  - mix smoke || travis_terminate 1
